### ISSUE TITLE
Share dvol volume support swarm or multi host use case

### ISSUE THREAD

**Issue by overmike** [ClusterHQ/dvol#61]
Existing implementation require dvol volume to be local, is there any planning to support swarm cluster?

**Comment by lukemarsden** [comment]
Hey @overmike! This is an interesting suggestion. How would you use dvol if it was possible to use it with swarm? If you can describe the use-case, that would be super helpful. Thanks!

**Comment by overmike** [comment]
my use case is about to share the dvol to other developer in their local machines. and also if I am thinking if it is possible to have version control on user file data.
